import useSWRInfinite from "swr/infinite"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
	const fetchSavedPosts = async () => {
		const bodyData = { currentPostFullname: "t3_rtuh19" }
		try {
			const response = await fetch(
				"http://localhost:3000/api/saved-posts-dev",
				{
					method: "POST",
					headers: {
						"Content-Type": "application/json",
					},
					body: JSON.stringify(bodyData),
				}
			)
			const data = await response.json()
			return data
		} catch (error) {
			console.log(error)
			return error
		}
	}

	const getKey = () => {
		return `/api/saved-posts-dev/1`
	}
	const { data, error, size, setSize } = useSWRInfinite(getKey, fetchSavedPosts)

	const handleFetchMore = () => setSize(size + 1)
	if (error)
		return (
			<p>
				Wow, you have terrible taste. We can&lsquo;t work with this!
				<p>
					Just kidding--there was a problem. That&lsquo;s our bad. Your saved
					posts are probably amazing.
				</p>
			</p>
		)
	if (!data) return <p>Loading...</p>

	if (data) {
		console.log(data[0].data)
		console.log(data)
		// data[0].map((item) => console.log(item))
		return (
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<h1>Hello!</h1>
				{/* {data &&
					data.data.map((item) => (
						<article key={item.name}>{item.subreddit}</article>
					))} */}
				<button className="fetch-more" onClick={handleFetchMore}>
					Fetch More
				</button>
			</div>
		)
	}
}
