import useSWR from "swr"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
	// const fetchData = async (path, token) => {
	// 	try {
	// 		const response = await fetch(path, {
	// 			headers: {
	// 				Authorization: `Bearer ${token}`,
	// 				"User-Agent":
	// 					"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0",
	// 			},
	// 		})
	// 		const data = await response.json()
	// 		console.log(data)
	// 		return data
	// 	} catch (error) {
	// 		console.log(error)
	// 		return await error
	// 	}
	// }

	// const { data, error } = useSWR(
	// 	`https://abdev-cors-anywhere.herokuapp.com/https://oauth.reddit.com/user/${process.env.NEXT_PUBLIC_REDDIT_USER}/saved`,
	// 	fetchData(
	// 		`https://abdev-cors-anywhere.herokuapp.com/https://oauth.reddit.com/user/${process.env.NEXT_PUBLIC_REDDIT_USER}/saved`,
	// 		process.env.NEXT_PUBLIC_REDDIT_OAUTH_TOKEN
	// 	)
	// )
	const fetchData = (url) =>
		fetch(url, {
			headers: {
				Authorization: `Bearer ${process.env.NEXT_PUBLIC_REDDIT_OAUTH_TOKEN}`,
				"User-Agent":
					"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0",
			},
		})
			.then((response) => response.json())
			.then((response) => console.log(response))

	const { data, error } = useSWR(
		`https://abdev-cors-anywhere.herokuapp.com/https://oauth.reddit.com/user/${process.env.NEXT_PUBLIC_REDDIT_USER}/saved`,
		fetchData
	)
	if (error) return <p>{error}</p>
	if (!data) return <p>Loading...</p>

	if (data) {
		return (
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				{data &&
					data.children.map((item) => (
						<article key={item.name}>{item.subreddit}</article>
					))}
			</div>
		)
	}
}
