import useSWR from "swr"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/home.module.css"

import PostFeed from "../components/feed/PostFeed"
import PostCard from "../components/feed/PostCard"

export default function Home() {
	const fetchData = async () => {
		const bodyData = { currentPostFullname: "t3_rtuh19" }
		try {
			const response = await fetch(
				"http://localhost:3000/api/saved-posts-dev",
				{
					method: "POST",
					headers: {
						"Content-Type": "application/json",
					},
					body: JSON.stringify(bodyData),
				}
			)
			const rawData = await response.json()
			const indexedData = await rawData.data.map((post, postIndex) => ({
				...post,
				initialIndex: postIndex,
			}))

			const data = indexedData.flat(3)

			return data
		} catch (error) {
			console.log(error)
			return error
		}
	}

	const { data, error } = useSWR("/api/saved-posts-dev", fetchData)

	// if (error)
	// 	return (
	// 		<p>
	// 			Wow, you have terrible taste. We can&lsquo;t work with this!
	// 			<p>
	// 				Just kidding--there was a problem. That&lsquo;s our bad. Your saved
	// 				posts are probably amazing.
	// 			</p>
	// 		</p>
	// 	)

	if (!data) return <p>Loading...</p>

	if (data && typeof data !== undefined) {
		// console.log(data.flat(3))
		// console.log(data.forEach((set) => console.log(set.data)))
		// data[0].data.map((item) => console.log(item.preview.enabled))
		return (
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<h1>Hello!</h1>

				{data[0] && <PostFeed data={data} />}
			</div>
		)
	}
}
// export async function getServerSideProps() {
// 	const bodyData = { currentPostFullname: "t3_rtuh19" }
// 	try {
// 		const response = await fetch("http://localhost:3000/api/saved-posts-dev", {
// 			method: "POST",
// 			headers: {
// 				"Content-Type": "application/json",
// 			},
// 			body: JSON.stringify(bodyData),
// 		})
// 		const rawData = await response.json()
// 		const indexedData = await rawData.data.map((post, postIndex) => ({
// 			...post,
// 			initialIndex: postIndex,
// 		}))

// 		const data = indexedData.flat(3)

// 		return { props: { data } }
// 	} catch (error) {
// 		console.log(error)
// 		return error
// 	}

// 	// Pass data to the page via props
// }
